### ISSUE TITLE
[Question] Network status

### ISSUE THREAD

**Issue by akhakha** [cruzbit/cruzbit#1]
Is this in testnet or mainnet currently?

**Comment by asdvxgxasjab** [comment]
Hello. I suppose you could call it mainnet but it is very experimental! Thanks for your interest.

**Comment by akhakha** [comment]
Thanks.

**Comment by asdvxgxasjab** [comment]
If you're the user who has added significant hash power to the network, I wanted to suggest that you could use multiple keys instead of mining to the single key. It improves privacy. There is a `genkeys` and `dumpkeys` command in the wallet that can be used to create a file full of public keys which the client can take as a `-keyfile` argument instead of a single `-pubkey`.
